import { Router } from 'express';
import userController from '../controllers/user.controller';
const routes = Router();
routes.post('/create-resource', userController.createResource);
routes.post('/update-resource', userController.updateResource);
routes.get('/resource-detail', userController.getResourceDetail);
routes.get('/list-resource', userController.listResource);
routes.get('/list-all', userController.listAll);
routes.delete('/delete-one', userController.deleteOne);
routes.delete('/delete-many', userController.deleteMany);
export default routes;